version: '3.6'

services: 
  web: 
    build: .
    #command: python /task/manage.py runserver 0.0.0.0:8000
    command: gunicorn collab_project.wsgi -b 0.0.0.0:8000
    environment: 
      - ENVIRONMENT=production
      - SECRET_KEY=wgd40#_k7dij%4yx=a8b-c!1e-w9sh2h&&%=w-z496sxap%c)j
      - DEBUG=0
    volumes:
      - .:/task
    ports: 
      - 8000:8000
    depends_on: 
      - db
  db:
    image: postgres:11
    container_name: pz01
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=collaboratory
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#   redis:
#     image: redis:latest
#     container_name: rz01
#     ports:
#       - "6379:6379" 
#   celery:
#     build: .
#     command: celery -A collab_project worker -l info
#     volumes:
#       - .:/task
#     depends_on:
#       - db
#       - redis
  

volumes: 
  postgres_data: