# Generated by Django 3.0.2 on 2020-02-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formset_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isbn_number', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
