# Generated by Django 3.0.2 on 2020-02-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('votes', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1500, verbose_name='Message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Is approved')),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('question_body', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('votes', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
