# Generated by Django 3.0.2 on 2020-01-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_body',
            field=models.TextField(),
        ),
    ]
