# Generated by Django 3.0.2 on 2020-03-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0002_auto_20200207_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
    ]
