# Generated by Django 3.0.2 on 2020-01-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0002_auto_20200125_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(),
        ),
    ]
