# Generated by Django 3.0.2 on 2020-03-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0005_auto_20200302_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
