# Generated by Django 3.0.2 on 2020-01-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0006_auto_20200130_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(blank=True, default='', max_length=1500, null=True, verbose_name='Message'),
        ),
    ]
