# Generated by Django 3.0.2 on 2020-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0007_auto_20200131_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(blank=True, default='', max_length=1500, verbose_name='Message'),
        ),
    ]
