# Generated by Django 3.0.2 on 2020-03-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0007_auto_20200304_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
    ]
