# Generated by Django 3.0.2 on 2020-03-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0009_answer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created_by',
        ),
    ]
