# Generated by Django 2.2 on 2020-03-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0010_remove_answer_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id']},
        ),
    ]
